### ISSUE TITLE
avatargpu tests fail due to NumPy 2.0 binary incompatibility

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#652]
**Describe the bug**
There is a binary incompatibility introduced by NumPy 2.0 that causes Python packages compiled against older NumPy versions to fail at runtime. This causes several GPU tests to fail on avatargpu.

This should be fixed by recompiling and reinstalling `h5py` and other Python packages that depend on NumPy's C API.

**To Reproduce**
1. Run avatargpu CI
2. See error:
```
36/40 Test #36: ComputePerturbations ..............***Failed    0.16 sec
Traceback (most recent call last):
  File "/tmp/bwibking/_work/1/s/src/perturbation.py", line 1, in <module>
    import h5py
  File "/home/bwibking/.local/lib/python3.9/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
  File "h5py/_errors.pyx", line 1, in init h5py._errors
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

      Start 37: PopIII
Failed test dependencies: ComputePerturbations
37/40 Test #37: PopIII ............................***Not Run   0.00 sec
      Start 38: ComputeStarClusterPerturbations
38/40 Test #38: ComputeStarClusterPerturbations ...***Failed    0.12 sec
Traceback (most recent call last):
  File "/tmp/bwibking/_work/1/s/src/perturbation.py", line 1, in <module>
    import h5py
  File "/home/bwibking/.local/lib/python3.9/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
  File "h5py/_errors.pyx", line 1, in init h5py._errors
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

      Start 39: StarCluster
Failed test dependencies: ComputeStarClusterPerturbations
39/40 Test #39: StarCluster .......................***Not Run   0.00 sec
      Start 40: SphericalCollapse
40/40 Test #40: SphericalCollapse .................   Passed  415.52 sec

90% tests passed, 4 tests failed out of 40
```

**Additional context**
https://numpy.org/doc/stable/dev/depending_on_numpy.html#numpy-2-abi-handling

**Comment by BenWibking** [comment]
Fixed by running:
```
pip uninstall h5py
pip install h5py
```
