### ISSUE TITLE
ComputePerturbations fails due to NumPy 2.0 API changes

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#653]
**Describe the bug**
NumPy 2.0, for no discernable reason, changed the names of its functions. This causes the Python script to generate perturbations to fail with an error.

For example, `np.product` has changed name to become `np.prod`.

**To Reproduce**
1. Run the test suite with NumPy 2.0 installed.
2. See error:
```
36/40 Test #36: ComputePerturbations ..............***Failed    0.96 sec
2 32
Traceback (most recent call last):
  File "/tmp/bwibking/_work/1/s/src/perturbation.py", line 289, in <module>
    pertx, perty, pertz = make_perturbations(n, kmin, kmax, f_solenoidal)
  File "/tmp/bwibking/_work/1/s/src/perturbation.py", line 128, in make_perturbations
    pertx, perty, pertz = normalize(pertx, perty, pertz)
  File "/tmp/bwibking/_work/1/s/src/perturbation.py", line 72, in normalize
    norm = np.sqrt(np.sum(fx**2 + fy**2 + fz**2)/np.product(n))
  File "/home/bwibking/.local/lib/python3.9/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'product'

      Start 37: PopIII
Failed test dependencies: ComputePerturbations
37/40 Test #37: PopIII ............................***Not Run   0.00 sec
      Start 38: ComputeStarClusterPerturbations
38/40 Test #38: ComputeStarClusterPerturbations ...***Failed    3.43 sec
2 64
Traceback (most recent call last):
  File "/tmp/bwibking/_work/1/s/src/perturbation.py", line 289, in <module>
    pertx, perty, pertz = make_perturbations(n, kmin, kmax, f_solenoidal)
  File "/tmp/bwibking/_work/1/s/src/perturbation.py", line 128, in make_perturbations
    pertx, perty, pertz = normalize(pertx, perty, pertz)
  File "/tmp/bwibking/_work/1/s/src/perturbation.py", line 72, in normalize
    norm = np.sqrt(np.sum(fx**2 + fy**2 + fz**2)/np.product(n))
  File "/home/bwibking/.local/lib/python3.9/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'product'
```

**Additional context**
See https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#main-namespace

**Comment by BenWibking** [comment]
cc @psharda @markkrumholz
